### ISSUE TITLE
feature request . when you click from the main screen to grayscale

### ISSUE THREAD

**Issue by Wjxfi** [tahaak67/Farhan#15]
for non-root users show the command `pm grant ly.com.tahaben.farhan android.permission.WRITE_SECURE_SETTINGS`. now there is only a "request root" button. I propose to make a "I don't have root" button and after clicking on it show this command with the option to copy. This is needed for adb. With the advent of android 12 it became possible to just use wi-fi to connect adb. This gives users the ability to use adb.

The most popular applications for this are ashell, ladb

**Comment by tahaak67** [comment]
since you see the use root button i assume your device is rooted right?, the app should only show that option if root is detected or else it will just show a button that will take you to a web page with instructions on how to grant the permission with ADB.

**Comment by tahaak67** [comment]
hmmm, well this shouldn't happen, i will look into it.
Thanks for reporting.

**Comment by tahaak67** [comment]
The root detection method is now changed to different one that has more success rate, also even if root detected an option to show how to grant the permission with ADB will be shown to users :)
