### ISSUE TITLE
It takes a very long time to load

### ISSUE THREAD

**Issue by Wjxfi** [tahaak67/Farhan#20]
farhan>usage>today

more than ten seconds to load the time information! Too much

I have minecraft, standoff (big games) load faster than your app😄

I have to wait for 3 seconds when moving to another day

(android 12 miui 13.0.5)

**Comment by tahaak67** [comment]
Please update to latest release the issue should be fixed

**Comment by tahaak67** [comment]
Hi again got not update from you so i hope you are fine
I'm going to close this issue since its fixed in the release.
feel free to comment if you have feedback or updates regarding the issue.
