### ISSUE TITLE
feature req. write something under "usage" or make the inscription bigger

### ISSUE THREAD

**Issue by Wjxfi** [tahaak67/Farhan#22]
now it is asymmetrical, the "issue" square looks empty
![320740.jpg](https://user-images.githubusercontent.com/113500363/222257018-aa5d89f5-1bd2-411f-96e3-22a09a8491fc.jpg)

**Comment by tahaak67** [comment]
This will be worked on with the new design planned :)
Your attention to details and interest in making Farhan better is very appreciated <3

**Comment by tahaak67** [comment]
Design updated with version 0.2.0
Closing
