### ISSUE TITLE
Bug on video (wrong usage)

### ISSUE THREAD

**Issue by Wjxfi** [tahaak67/Farhan#23]
I twisted the screen (like in the video) and the values changed 
It was fine before that

https://user-images.githubusercontent.com/113500363/222887132-32797f30-ee9d-40f4-9781-64374dc83e04.mp4

the problem (appeared) is at the bottom of the list
![Polish_20230304_121218763.jpg](https://user-images.githubusercontent.com/113500363/222889553-0b65d16a-5fe5-4245-9465-77a6372d17d9.jpg)

**Comment by tahaak67** [comment]
Hi again got not update from you so i hope you are fine
I'm going to close this issue since its fixed in the release.
feel free to comment if you have feedback or updates regarding the issue.
