### ISSUE TITLE
feature req. round corners

### ISSUE THREAD

**Issue by Wjxfi** [tahaak67/Farhan#27]
![322175.jpg](https://user-images.githubusercontent.com/113500363/222932643-a3272042-2ae9-4acb-8e5a-1a689ae6c57f.jpg)

![322177.jpg](https://user-images.githubusercontent.com/113500363/222932644-be95e3fd-bc7c-44f9-80a6-a82a21e50376.jpg)

**Comment by tahaak67** [comment]
can you explain more what's the problem here?

**Comment by tahaak67** [comment]
Thanks for your suggestion, Wjxfi. The menu currently has the default radius specified by the [Material Design guidelines](https://m3.material.io/components/menus/specs#500d5b66-9b09-4f2a-b900-80103ebf4cb9), which are based on user research and design best practices. Adding more radius might detract from the app's design and make the menu appear too large or out of proportion with other elements in the app. However, I appreciate your feedback and am always open to hearing more. Thanks again!
