### ISSUE TITLE
With Greyscale whitelist disabled, all apps are greyscaled

### ISSUE THREAD

**Issue by shruuub** [tahaak67/Farhan#30]
Hi,
Thanks for the app, it is quite nice! However, enabling greyscale and adding most apps, then disabling it again, all apps stay and are greyscaled. The only option is to enable the whitelist and remove the app while having the whitelist enabled.

**Comment by tahaak67** [comment]
**Hi shruuub**, glad you liked Farhan 😊.
Thanks for pointing this out I'll work on fixing it in the next few patches.
**Meanwhile**, you should be able to avoid this behavior by removing Farhan from the whitelist before disabling grayscale.

**Comment by shruuub** [comment]
> Meanwhile, you should be able to avoid this behavior by removing Farhan from the whitelist before disabling grayscale.

Yup, that works! Guess I will keep the issue open until it's fixed for information though.

**Comment by shruuub** [comment]
Nice! Works flawlessly now, thanks a lot!
