### ISSUE TITLE
[Bug] Notify me not working on android 13+

### ISSUE THREAD

**Issue by pabloscloud** [tahaak67/Farhan#48]
I've set the Notification for the Notication Filter to 7 o'clock in the morning but I just don't get the notification.

**Comment by tahaak67** [comment]
can you provide a screen shot of Notification filter settings screen?

**Comment by pabloscloud** [comment]
![0f460bab-4c67-4014-9437-d59cccff7025](https://github.com/tahaak67/Farhan/assets/93644977/340c1200-d17c-468f-a8b6-b4bad835fbc5)

For sure :)

**Comment by tahaak67** [comment]
what android version are you on?

**Comment by pabloscloud** [comment]
14

**Comment by pabloscloud** [comment]
> what android version are you on?

14

**Comment by tahaak67** [comment]
If you don't want to wait for the update you can open app info and grant the permissions manually
Notify me needs notifications and  (Alarm & reminder) permissions.

**Comment by pabloscloud** [comment]
Notifications had been on before. Enabled Alarms and Reminders permission now. I'll see how it goes. Thanks for the tip tog et it working before the update. And thanks for being so responsive in general :)

**Comment by pabloscloud** [comment]
Works for me :) thanks for the quick fix
